# -*- coding: utf-8 -*-
"""instagram_ac_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QV2WDz6S8Q3MrhaEfl8uMDEZEIzGOVH5
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("instagram.csv")

print(df.head())
print(df.shape)

print(df.isnull().sum())

X = df.drop("fake", axis=1)
y = df["fake"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

print(
    importance.sort_values(
        by="Importance",
        ascending=False
    )
)

import joblib

joblib.dump(model, "instagram_fake_detector.pkl")

print("Model Saved Successfully")

